/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as AdminRoute } from "../../../packages/ui/src/routes/admin";
import type { User } from "@repo/db";

export const routeTree = rootRoute.addChildren([IndexRoute, AdminRoute]);
