// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission rules for boundaries.
 */
export type Permissions = { 
/**
 * Lists which tags are allowed.
 *
 * Any tag not included will be banned. If omitted, all tags are permitted.
 */
allow?: Array<string>, 
/**
 * Lists which tags are banned.
 */
deny?: Array<string>, 
/**
 * Lists external (npm) packages that are banned, by name or glob (e.g.
 * `"pg"`, `"@aws-sdk/*"`, `"drizzle-*"`).
 *
 * Checked against the external dependencies declared in the
 * `package.json` of the package and of each of its transitive workspace
 * dependencies (excluding their `devDependencies`). Only valid in
 * `dependencies` rules.
 */
denyPackages?: Array<string>, };
